apiVersion: v1
kind: Service
metadata:
  name: amani-service
  labels:
    app: amani-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"

spec:
  selector:
    app: amani-service
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: amani-service
  labels:
    app: amani-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: amani-service
  template:
    metadata:
      labels:
        app: amani-service
    spec:
      containers:
        - name: amani-service
          image: {{image}}
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 250m
          imagePullPolicy: Always
          env:
            - name: APP_NAME
              value: amani-service
          ports:
            - containerPort: 80
              protocol: TCP
